### ISSUE TITLE
rgt-hint differential stuck at generating line plots

### ISSUE THREAD

**Issue by idalarsson** [CostaLab/reg-gen#147] opened 2020-05-07 08:16 UTC
Hi!
I've been following your tutorial for generating footprints from atac-seq data (https://www.regulatory-genomics.org/hint/tutorial/?fbclid=IwAR3uQ76-2-cm1KpmpmphOx7YPzB-PYz3mCdXmgjhYVaZB5ybTjHfNh1GjhE). It's been working perfectly until step 5 where the code has been running for a really long time and I am wondering how long this step usually take (working on a 4 CPU laptop right now). The output messages says that signal generation is done and right now the message says "generating line plots for each motif", but from what I can see the lineplots were generated several hours ago. Did it get stuck or is this to be expected?

//Ida

**Comment by lzj1769** [comment] 2020-05-07 10:11
Hi,

> It's been working perfectly until step 5 where the code has been running for a really long time and I am wondering how long this step usually take (working on a 4 CPU laptop right now)

Did you enable the multi-precessing option? This step usually takes hours to finish.

**Comment by idalarsson** [comment] 2020-05-07 10:16
I think so? I used the command given in the tutorial, as below:
`rgt-hint differential --organism=hg19 --bc --nc 30`

**Comment by lzj1769** [comment] 2020-05-07 10:37
ok, I see.
I think the problem is your laptop has 4 CPUs, 
and you are asking rgt-hint to use 30 CPUs by `--nc 30`,
so, it's expected that rgt-hint needs more time for computation.

Try to take a cup of coffee and wait a few more hours, :)

**Comment by idalarsson** [comment] 2020-05-07 11:12
Ok thank you!

**Comment by lzj1769** [comment] 2020-05-26 20:24
I will close this issue. 
Feel free to re-open it if there are other questions.

**Closed by lzj1769** 2020-05-26 20:24 UTC
